# Generated by Django 4.2.4 on 2023-08-23 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='users',
            field=models.ManyToManyField(related_name='restaurants', to=settings.AUTH_USER_MODEL),
        ),
    ]
